version: "3.9"
services:
  db:
    image: "mysql:latest"
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - "bridge"

  setget-api:
    env_file:
      - ./.env
    container_name: setget-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    networks:
      - setget

networks:
  setget:
    driver: bridge
