apiVersion: v1
kind: Service
metadata:
  name: {{ include "setget.fullname" . }}
  {{- if .Values.namespace.enabled }}
  namespace: {{.Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "setget.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "setget.selectorLabels" . | nindent 4 }}