{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "setget.serviceAccountName" . }}
  {{- if .Values.namespace.enabled }}
  namespace: {{.Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "setget.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}